### ISSUE TITLE
New codegen/mixin based functions break tooling

### ISSUE THREAD

**Issue by ryuukk** [BindBC/bindbc-freetype#13]
We can no longer get code completion for these functions since they don't exist

I suggest avoiding doing that on popular packages as the user experience is not great as a result

I understand it is to facilitate making the binding, but perhaps the strategy could be made in 2 step so you could generate the files with the functions directly, so we have usable function definitions for tooling

**Comment by ichordev** [comment]
I can see how that might be doable using the mixin textual export feature (`-mixin`), but for these projects it would really disrupt my workflow. I can’t let the feature-set of third-party tools dictate which features I use.

However… it’s surely far from impossible to add mixin support on the end of these tools. Perhaps this could be implemented by simply scanning the output of the aforementioned `-mixin` feature? It would require trying to build at least once, but the build doesn’t have to fully succeed for the `-mixin` file to be generated. I could look into adding SublimeText support for this if that’s of interest to you—I dunno what settings or plugins people usually use for that so I’d have to figure that out.

**Comment by ichordev** [comment]
> It wasn't using mixin before, so this idea is a new one you introduced without asking for the users, this is bad, worsening the user experience
> 
> Please think about users, instead of just yourself

I am also a user of various BindBC libraries, including this one, which is why I updated it recently. I'm also the sole maintainer; most outside contributions I receive are small fixes. I do this because I enjoy it and because somebody has to keep these things up-to-date. It's time-consuming though, so function binding mixins (which reduced function code repetition by 5 times) are a necessary part of making this something that I can continue to do in my free time.

> Actually, `-vcg-ast` would be better, as it would also cover templates

I don't think I use enough templates for that to matter for BindBC libraries. In fact, I avoid templates wherever I can, preferring nested mixins if need be. Adding my project folder with the `-mixin` output in SublimeText is enough for it to start indexing it for auto-completion.
